### ISSUE TITLE
Not an issue - Test data set emotes

### ISSUE THREAD

**Issue by johndpope** [bchidest/RiCNN#1]
https://twitter.com/jakewprogrammer/status/1154195812580151301?s=21

I wondered if your rotation invariance could help with above use case - it maybe a great follow up research to explore.

**Comment by bchidest** [comment]
Hey @johndpope, thanks for your suggestion, and sorry I hadn't replied earlier! Though, it looks like the images only exhibit a minor amount of rotation, in which case, I don't expect it would yield a very substantial improvement.

**Comment by johndpope** [comment]
Are you working on a new paper? I have a radical approach to convolutional neural nets that I've been sitting on for some years. If you have an ear - would be happy to to voice it. It centers around real time processing on mobile being too computationally expensive to do traditionally.
